[[hooks]]
stage = "pre_build"
command = "cargo"
command_arguments = [
  "run",
  "-p",
  "lattice-css-build",
  "--",
  "--input",
  "app.src.css",
  "--output",
  "app.css",
]

[watch]
watch = ["app.src.css", "css", "src", "index.html"]
