global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: postgres
    static_configs:
      - targets:
          - postgres-exporter:9187

  - job_name: json-api
    static_configs:
      - targets:
          - json-api-dev:8698

  - job_name: alloy
    static_configs:
      - targets:
          - alloy:12345

  - job_name: tempo
    static_configs:
      - targets:
          - tempo:3200

  - job_name: loki
    static_configs:
      - targets:
          - loki:3100

  - job_name: pyroscope
    static_configs:
      - targets:
          - pyroscope:4040
